name: add mask to variables in workflow
on:
    workflow_dispatch:

jobs:
    add_mask_job:
        runs-on: ubuntu-latest
        steps:
            - name: set API_KEY
              run: echo "API_KEY=123456" >> $GITHUB_ENV

            - name: print API_KEY with mask
              run: |
                  echo "::add-mask::$API_KEY"
                  echo "The API key is $API_KEY"
