name: manual trigger
on:
    workflow_dispatch:
        inputs:
            env:
                description: "Select environment"
                required: true
                default: "staging"
                type: choice
                options:
                    - production
                    - staging
                    - development
            logLevel:
                description: 'Log level'
                required: true
                default: 'warning'
                type: choice
                options:
                  - info
                  - warning
                  - debug
            print_tags:
                description: 'True to print to STDOUT'
                required: true
                type: boolean
            tags:
                description: 'Test scenario tags'
                required: true
                type: string
#you’ll need to create environments in your repository settings (Settings → Environments → New environment).
#That’s where you define names, secrets, and rules. Once they exist, they’ll appear in that dropdown automatically.
            environment:
                description: 'Environment to run tests against'
                type: environment
                required: true
            number_of_runs:
                description: 'Number of times to run the tests'
                required: true
                default: 1
                type: number

jobs:
    display:
        runs-on: ubuntu-latest
        steps:
            - name: print with echo
              run: echo "hello, manual trigger on ${{ inputs.environment }} environment"
            
            - name: Show selected environment
              run: echo "Running against ${{ github.event.inputs.environment }}" 

            - name: Show log level
              run: echo "Selected log level  ${{ github.event.inputs.logLevel }}"
              